### PR TITLE
perf: don't use a placeholder as root in the default Caddyfile and add docs

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by dunglas** [comment]
No, but this will have the same effect.

**Comment by AlliBalliBaba** [comment]
`php_server` with `file_server off` will still do `try_files` (maybe this can be optimized in Caddy?).
The fastest configuration is just using `php` with a `rewrite` to the index file

Here's what I'm getting:

~66000 RPS
```
php_server {
	root /go/src/app/testdata
	file_server off
	enable_root_symlink false
}
```

~88000 RPS (+33%)
```
php {
	root /go/src/app/testdata
	enable_root_symlink false
}
```

**Comment by dunglas** [comment]
Not related, but would you mind to run the benchmark with 1.2.5 to compute the improvement? Thank you!

IMHO we shouldn't do a `try_file` if the `file_server` directive is off. It's likely a bug in our code.

**Comment by AlliBalliBaba** [comment]
Here's the flamegraphs for reference:

With `php`
flame-php

With `php_server`
flame

**Comment by dunglas** [comment]
Closing in favor of https://github.com/dunglas/frankenphp/pull/1154.

**Pull request closed without merging**
