### PR TITLE
more robust workaround for -d command line params

### PR DESCRIPTION
**Pull request by flexponsive**
unfortunately there were some corner cases (like first parameter not equal to -d) that are difficult to handle with sh. added a more robust workaround script (which requires bash) and made clear we have to set the PHP_BINARY env variable for this to work.

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thanks. The long term solution would be:

1. to automatically set the env var when running `frankenphp php-cli` (easy pick)
2. support `-d` (a bit more complicated, but basically some copy/paste/adapt from the official CLI SAPI to do)

**Comment by dunglas** [comment]
Technically, this would be possible to execute the `php-cli` subcommand if no explicit command is passed and arguments exist, but I fear that it would be confusing and error prone.

Creating a symlink or a tiny script that calls `frankenphp php-cli` would be very similar isn't it?

**Comment by flexponsive** [comment]
With the wrapper script, the potential problem is for frankenphp to know whether it is being called in the context of a wrapper script / where the wrapper script is. If I call `frankenphp php-cli composer install` directly on the terminal, is there a good way for frankenphp to know where the wrapper script could be?

Alternatively, one could make frankenphp behaved differently if it was called "php" rather than anything else (or called through a symlink named "php"). I was able to get this work on linux and mac, windows not tested (`invokedAs := filepath.Base(os.Args[0])`). So effectively frankenphp would bundle its own wrapper script. However, this behavior is also a little bit subtle.

**Comment by dunglas** [comment]
I'm a bit reluctant do add such hacks in FrankenPHP itself. Wouldn't it be more reliable and easier to add support for `php-cli` to Composer and Artisan directly?

**Comment by flexponsive** [comment]
For frankenphp to be mostly compatible with the existing command line arguments of php-cli (i.e. run `php -d memory_limit=1G myscript.php` through frankenphp) is really important for a smooth migration path in my view. Convincing other projects to add explicit support for frankenphp's existing CLI interface may be possible, but will delay and limit adoption of frankenphp (e.g. if things go well, laravel 12 may include frankenphp patches; if your legacy application has shell scripts calling php, you have to update them all, what about semi-proprietary stuff like Magento/Adobe Commerce)

The good news is that the command line interfaces of caddy/frankenphp and "classic" php do not conflict and hacks like `os.Args[0]` are not required; each user can decide whether to symlink frankenphp to php or not. 

## Suggested Change in Behavior

- If we receive command line arguments but no valid frankenphp/caddy command, default to `php-cli`
- In case of an error when loading the php script after defaulting to `php-cli` print a warning in addition to the error message
- Add support for at least the flags `-d`, `-i` and `-m` to improve support with legacy scripts

### Examples of proposed behavior:
```
$ frankenphp -d memory_limit=1G artisan
Laravel Framework 10.39.0

Usage:
...

$ frankenphp artisan queue:failed
   Illuminate\Database\QueryException

  SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused
...

$ frankenphp start-servers; echo $?
Warning: unknown command "start-servers"; defaulting to "php-cli"
Could not open input file: start-servers
1
```

### Comparison with existing behavior:

```
$ frankenphp start-servers; echo $?
Error: unknown command "start-servers" for "caddy"
1
```

What do you think about this solution? if you could consider a PR along these lines, I'd be happy to give it a try.

**Comment by dunglas** [comment]
@flexponsive let's merge this one for now.

Supporting `-d` would be cool and should be easy.
I'm less sure about the "default" behavior as it will create ambiguities but I have to think more about this.

**Comment by dunglas** [comment]
Thanks!

**Pull request merged**
