### PR TITLE
feat: add custom Caddy modules to the static binary

### LINKED ISSUE #591: Can't get custom modules to build
### What happened?

I can't get FrankenPHP to compile with HTTP cache module: https://github.com/caddyserver/cache-handler (or other popular caddy modules)

I'm building a WordPress Docker image where I'm hoping to beat benchmarks and stress tests of the standard WordPress Docker image. I've been using loader.io and FrankenPHP starts to get significantly slower than the standard Apache Docker Image. I believe it is due to some caching. Apache response times for Apache stay consistent no matter the load I throw at it.

I've updated to match the WordPress image defaults as much as possible. I've included & optimized Opcache, but it still gets up to 7-8 seconds when I send 1800 requests to my WordPress image in 1 minute. Comparably, the standard WordPress Apache version takes 450ms consistently.

So I believe it must be something with additional HTTP caching.

--

I'm trying to build FrankenPHP with this module: github.com/caddyserver/cache-handler , but its throwing back C errors that I just can't understand. I've tried other modules but still have similar issues.

I'm attaching the build errors  in the log output below.

Thanks! I'm really enjoying this project. 

### Build Type

Docker (Debian Bookworm)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### Relevant log output

```shell
#11 38.58 go: downloading google.golang.org/appengine v1.6.7
#11 39.04 2024/02/23 15:49:06 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /usr/local/bin/frankenphp -ldflags -w -s
#11 60.97 # caddy
#11 60.97 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
#11 60.97 /usr/bin/ld: /tmp/go-link-3153015539/000017.o: warning: relocation against `stderr@@GLIBC_2.2.5' in read-only section `.text'
#11 60.97 /usr/bin/ld: /tmp/go-link-3153015539/000009.o: relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a PDE object; recompile with -fPIE
#11 60.97 /usr/bin/ld: final link failed: bad value
#11 60.97 collect2: error: ld returned 1 exit status
```

### LINKED ISSUE #982: Question: how to build a standalone frankenphp binary with Caddy cache-handler
Hello,

On production we're currently using the [frankenphp standalone binaries](https://github.com/dunglas/frankenphp/releases/latest/download/frankenphp-linux-x86_64) with the Api Platform distribution.

Unfortunately (see https://github.com/dunglas/frankenphp/issues/956#issuecomment-2271581693), there is no frankenphp binaries distributed with HTTP cache into Caddy, no problem with that, @dunglas and @darkweak explained well why)

On local / development environment, we found a way to build a `frankenphp` binary with HTTP cache on Docker (thanks to `xcaddy build`, see https://github.com/dunglas/frankenphp/issues/976#issuecomment-2296049125)

```
FROM dunglas/frankenphp:latest-builder AS builder
COPY --from=caddy:builder /usr/bin/xcaddy /usr/bin/xcaddy

RUN apt-get update && apt-get install --no-install-recommends -y \
    git

ENV CGO_ENABLED=1 XCADDY_SETCAP=1 XCADDY_GO_BUILD_FLAGS="-ldflags \"-w -s -extldflags '-Wl,-z,stack-size=0x80000'\""
RUN xcaddy build \
    --output /usr/local/bin/frankenphp \
    --with github.com/dunglas/frankenphp=./ \
    --with github.com/dunglas/frankenphp/caddy=./caddy/ \
    --with github.com/dunglas/mercure/caddy \
    --with github.com/dunglas/vulcain/caddy \
    --with github.com/dunglas/caddy-cbrotli \
    --with github.com/darkweak/souin/plugins/caddy@65cb24114d76a7de3f4e8c7b8ef7df3efd028899 \
    --with github.com/darkweak/souin@65cb24114d76a7de3f4e8c7b8ef7df3efd028899 \
    --with github.com/darkweak/storages/otter/caddy

FROM dunglas/frankenphp:latest AS frankenphp_upstream
COPY --from=builder --link /usr/local/bin/frankenphp /usr/local/bin/frankenphp
```

It works well on the Symfony prod env under Docker but we're not using Docker on our production server 😁

Naively, I try to extract the binary built on Docker (`docker cp {containerId}:/usr/local/bin/frankenphp frankenphp-http-cache`), then transferring the executable on my production server (Ubuntu 20 LTS) and trying to use it 🙄

```
sudo +x frankenphp-http-cache
./frankenphp-http-cache -v
> ./frankenphp-http-cache: error while loading shared libraries: libphp.so: cannot open shared object file: No such file or directory
```

You'll tell me *"it's not the same architecture, Debian versus Ubuntu, etc."* and you're probably right 🙂

So my question is simple: how can I build and use a standalone frankenphp binary with HTTP cache packaged in the Caddy web server?

I read the chapter [Create a Static Build](https://frankenphp.dev/docs/static/#customizing-the-build) in the doc but I see nothing to add extra caddy plugins (Souin) on the fly with the [`build-static.sh`](https://github.com/dunglas/frankenphp/blob/main/build-static.sh) but maybe I'm wrong, I'm really new into the Go/Caddy ecosystems 😑

I also see [these lines](https://github.com/dunglas/frankenphp/blob/main/caddy/go.mod#L9-L18), I guess I can add (without much conviction) the Caddy plugins (`darkweak/souin`, `darkweak/souin/plugins/caddy` and `darkweak/storages/otter/caddy`) to this list and try to use the static-builder provided with the docker image?

If there is a a simpler method, any help would be welcome 👍 

Thanks a lot

### LINKED ISSUE #1208: Documentation: how to build static binaries with caddy modules included
The script to build static binaries builds frankenphp directly. 
Is there any way to build it with caddy modules included?

### PR DESCRIPTION
**Pull request by dunglas**
Add custom Caddy modules to static binaries.

Example with Souin, Mercure and Vulcain:

```
XCADDY_ARGS="--with github.com/darkweak/souin/plugins/caddy --with github.com/dunglas/mercure/caddy --with github.com/dunglas/vulcain/caddy"  \
./build-static.sh
```

Closes #1208, closes #982, closes #591.

TODO:

* [x] docs

### CODE REVIEW

**Review by withinboredom — APPROVED** [review]

**Comment by dunglas** [comment]
The error in the CI is super weird

**Comment by vittodevit** [comment]
Tried testing the branch locally but the error is exactly the same.
It seems to crash at one of the last steps of the `static-build.sh` file when it's defining the environment variables?
image

**Comment by vittodevit** [comment]
Ok, i found the time to do a couple more tests.
Without using the container, i ran directly the build-static.sh file and this is where it crashes: https://dpaste.com/6NVEGLWN2
The env i used is this: https://dpaste.com/HTVXLJM84
Running it without the env gives the exact same error.

**Comment by dunglas** [comment]
This seems to work now, but I'm not sure why...

**Pull request merged**
