### PR TITLE
Add docs for custom docker image

### PR DESCRIPTION
**Pull request by alexander-schranz**
I'm missing something like this in the docs.

### CODE REVIEW

**Comment by dunglas** [comment]
Can't we merge this with the existing docs about Docker in a "Docker" section?

**Comment by alexander-schranz** [comment]
@dunglas Yeah I was not sure to mix them up. I think the currenlty `docker.md` is focused for Contributers or Maintaincers of FrankenPHP not about the one using it.

I even think `worker.md` linked as `The worker mode` is misleading and should be called `Getting Started` instead or `Using FrankenPHP` and then maybe add it there?

Also I personally more a fan to have one bigger `doc` file instead of splitting the docs into multiple files make searching for specific things easier and think why also Symfony merged a lot of docs together in the last years.

**Comment by back-2-95** [comment]
I was also thinking about docs like this. But this is really different thing than the current content of `docker.md`.

Maybe something like "Extending FrankenPHP" ?

**Comment by dunglas** [comment]
Or just a new section at the end: "Creating Your Own Images"?

**Comment by dunglas** [comment]
Thank you @alexander-schranz!!

**Pull request merged**
