### PR TITLE
add performance math to docs

### PR DESCRIPTION
**Pull request by withinboredom**
This adjusts the docs around performance along with some recommendations.

### CODE REVIEW

**Comment by withinboredom** [comment]
IRT #269

I'd like to be able to automatically calculate GOMEMLIMIT, thread/worker count, and php's `memory_limit` -- even setting them on the fly; with logging.

But this PR consolidates what we know so far with tuning -- I think.

**Comment by withinboredom** [comment]
I've got pretty diagrams coming in a different branch.

**Comment by bendavies** [comment]
@withinboredom are they viewable somewhere? :)

**Comment by withinboredom** [comment]
@bendavies They're on a branch on my computer :) I keep meaning to ask @dunglas if mermaidjs rendering is available on the website but keep forgetting. I guess now is as good time as any! 

@dunglas, is mermaidjs rendering available on the website (or where is the site being rendered at)? I'd be happy to tackle that.

**Comment by bendavies** [comment]
@dunglas see above!

**Comment by dunglas** [comment]
It looks supported: https://gohugo.io/content-management/diagrams/

**Comment by bendavies** [comment]
did this ever get picked up elsewhere?
seems reasonably important to document

**Pull request closed without merging**
