### PR TITLE
Add Turkish translated docs files

### PR DESCRIPTION
**Pull request by mertingen**
For the documents, I translated a total of 14 files from English to Turkish.

### CODE REVIEW

**Comment by dunglas** [comment]
Thank you very much @mertingen! That's so cool that we're getting translations in many languages.

I made the linters happy and fixed some tiny issues (some markup needs to stay in English to be understood by the GitHub parser).

The last step is to add a new `tr.yaml` file here to translate the extra strings needed for the website: https://github.com/dunglas/frankenphp-website/tree/main/i18n
Can you open a PR in this repo too?

**Comment by mertingen** [comment]
> Thank you very much @mertingen! That's so cool that we're getting translations in many languages.
> 
> I made the linters happy and fixed some tiny issues (some markup needs to stay in English to be understood by the GitHub parser).
> 
> The last step is to add a new `tr.yaml` file here to translate the extra strings needed for the website: https://github.com/dunglas/frankenphp-website/tree/main/i18n Can you open a PR in this repo too?

**Comment by mertingen** [comment]
Thanks @dunglas ,

I closed this PR by mistake, sorry. By the way, I created the file you mentioned.

https://github.com/dunglas/frankenphp-website/pull/16

**Comment by dunglas** [comment]
Thank you very much!

**Pull request merged**
