### PR TITLE
Alpine image

### LINKED ISSUE #42: Alpine image
I just re-did `Dockerfile` with alpine images:

CleanShot 2022-10-19 at 23 25 27@2x

From 2.51 Gb (Bullseye) to 256 Mb (Alpine)

I need to cleanup my work and create PR.

### PR DESCRIPTION
**Pull request by back-2-95**
- Alpine variant of the Docker image
- Docker Bake definition file to build Bullseye and Alpine images for amd64 and arm64
- Docs

See the `docs/docker.md` for how to test.

Needs some validation that `Dockerfile.alpine` has all the stuff correctly as package names and some operations are different in Alpine.

Note: Some command chains are broken down to separate `RUN` lines as in build stages there is no point and separate lines make it faster to debug and use working layers.

Resolves #42

### CODE REVIEW

**Comment by dunglas** [comment]
Thanks for your very appreciated contribution! Do you think that it would be possible to use a template file to build both variants, as done in the official Docker PHP repo? https://github.com/docker-library/php/blob/master/Dockerfile-linux.template

**Comment by back-2-95** [comment]
I was thinking to utilize stages and build targets in bake file further as it's easier to read. Here is example where I create different kind of PHP variants from same Dockerfile: https://github.com/druidfi/docker-images/tree/main/php

It creates 3 PHP minor versions, base php, fpm, drupal, drupal+nginx, all for amd64/arm64.

But I think it could be something for other PR. Sometimes avoiding DRY goes too far 😅

I'd appreciate if `Dockerfile` and `Dockerfile.alpine` would be diffed to see if all major steps are there.

Also I was thinking it the ARGs I added here could be used in original Dockerfile too?

These:

```
ARG PHP_BASE_IMAGE
ARG PHP_SRC_REPO
ARG PHP_SRC_BRANCH
```

**Comment by dunglas** [comment]
I would prefer to be as close as possible from the images and the tooling from the official images to reduce the maintenance burden. The long term goal is to get rid at least of the PHP build stage anyway and use official images instead.

**Comment by back-2-95** [comment]
That is true. I guess the the most heavy stage will be removed when php-src will include those few changes?

**Comment by back-2-95** [comment]
I checked the "template-engine" from that official PHP source. It would quite an effort to learn that and incorporate here (even if that is just shell script based thing).

And if we get to situation where we can remove the php-src build stage all together, it would become obsolete.

It seems also that they have 4 distro variants: 2 alpines, Buster and Bullseye.

When we could rely on official PHP base images here as they are, this will come super simple and readable setup where we can create easily images for different PHP versions like 8.2, 8.3 and those officially supported distros + architectures.

**Comment by back-2-95** [comment]
Pulled the latest changes and updated PR accordingly.

**Comment by back-2-95** [comment]
@dunglas do you expect that those Frankenphp commits from https://github.com/php/php-src.git and branch `PHP-8.2` will be included in the next PHP 8.2.0RC5 maybe?

**Comment by dunglas** [comment]
Shouldn't we also update the GitHub Actions setup?

Could you also remove the args, please? It will make the image consistent with the Debian variant and limit the possible unintended side effects. We'll remove this stage anyway as soon as a new 8.2 version will be tagged and https://github.com/docker-library/php/pull/1331 merged.

**Comment by back-2-95** [comment]
@dunglas done 👍

**Comment by back-2-95** [comment]
@dunglas and the GHA setup updated too

**Comment by back-2-95** [comment]
Tested both images with [Demo app (Symfony) and benchmarks](https://github.com/dunglas/frankenphp-demo) locally with my M1 Macbook Pro (arm64 images). Demo works the same with both images.

**Comment by dunglas** [comment]
Thank you very much @back-2-95!

**Pull request merged**
