### PR TITLE
perf: $_SERVER known variables optimizations

### PR DESCRIPTION
**Pull request by AlliBalliBaba**
This PR attempts some more performance improvements on the $_SERVER import.

[php_register_variable_safe](https://github.com/php/php-src/blob/39fa9cfd1a0ecc486207c1211bf0327840f4e30f/main/php_variables.c#L108) does a lot of checking to see if a variable name is safe to import. This checking mainly focuses on validating the key for POST/GET or validating HEADER names or COOKIES.

The keys for the 'known server variables' are hard coded though so this validation is largely unnecessary. Additionally, we can re-use the keys between requests to avoid unnecessary allocations.

These variables should be safe to import always, since they come from go without any real user input:

[CONTENT_LENGTH][DOCUMENT_ROOT][DOCUMENT_URI][GATEWAY_INTERFACE][HTTPS][REMOTE_ADDR][REMOTE_HOST[REMOTE_PORT][REQUEST_SCHEME][SCRIPT_FILENAME][SCRIPT_NAME][SERVER_NAME][SERVER_PORT[SERVER_PROTOCOL][SERVER_SOFTWARE][SSL_PROTOCOL][AUTH_TYPE][REMOTE_IDENT]

The only values I'm currently not sure about are these 3, since they potentially contain user input. I know that these values are sanitized by `net/http`, but I want to be absolutely sure I'm not missing anything here:

[PHP_SELF] - contains the path sent by the user (after the script)
[PATH_INFO] - contains the path sent by the user
[HTTP_HOST] - containes the host header sent by the user

As shown in the flamegraphs, this makes variables importing on the C side almost 3 times as fast (the long yellow runtime.Cgo call):

Without this PR:
flame

With this PR:
flame

### CODE REVIEW

**Comment by AlliBalliBaba** [comment]
I realized that the slowness doesn't come from `php_register_variable_safe`, but actually from `sapi_module.input_filter`, which is necessary for something like this to work:
```
$phpSelf = filter_input(INPUT_SERVER, "PHP_SELF")
```

This is a bit unfortunate, it looks like PHP is actually storing all of these values twice. I'll look into it a bit further, if this can't be optimized, I'll at least add some tests

**Comment by dunglas** [comment]
Yes I also noticed this. And this feature is really niche, I think almost nobody use it. Maybe should we provide a flag to disable it (or even make it opt-in through a php.ini setting?)

**Comment by AlliBalliBaba** [comment]
I think I'm fine with making this opt-in since also none of the major frameworks seem to be using it. Searching for it mostly leads to very old issues recommending against its usage (like [this one](https://github.com/10up/Engineering-Best-Practices/issues/132) or [this one](https://github.com/xwp/stream/issues/254)). I'll try creating a minimal implementation without it

**Comment by dunglas** [comment]
It's usable only with a custom PHP extension.

**Comment by AlliBalliBaba** [comment]
I tried adding a '`fringe_mode`' config that enables this feature. I'm not yet sure how much I like having such a mode, but maybe there are other features that would fit into it.

Disabling `sapi_module.input_filter(PARSE_SERVER` everywhere makes the import even faster.

With `fringe_mode`
flame_fringe_mode

Without `fringe_mode`
flame

PS: still not sure why checks are not triggering for my PRs anymore. Is it cause I'm merging from a fork?

**Comment by dunglas** [comment]
I would disable this feature by default and add a specific flag to enable it. Having a global feature flag will prevent cherry-picking the specific options the user may need.

Initially, FrankenPHP wasn't supporting this feature. I added support for it for consistency with other SAPIs, but nobody asked for it and I'm almost sure nobody use it...

For the checks, that's maybe because the PR is still a draft?

**Comment by AlliBalliBaba** [comment]
By flag you mean a build flag like with the watcher and brotli?

I'll probably also try going all the way and refactor registering globals so everything happens in `cgi.go` if that's ok with you. Looking at the flamegraphs, I think the additional overhead of the Cgo calls doesn't matter much.

I think the checks might be github bug, if they don't trigger I'll try again from a different branch

**Comment by dunglas** [comment]
No sorry, I mean a Caddyfile config option. We can do the check at runtime, it's just a if that will cost virtually nothing.

**Comment by AlliBalliBaba** [comment]
Replaced by #1106

**Pull request closed without merging**
