### PR TITLE
feat: rename `DEBUG` env var to `CADDY_DEBUG`

### LINKED ISSUE #57: Consider renaming DEBUG env var
In the built-in Caddyfile, there is a built-in `DEBUG` env var injected. This is quite generic and may conflict with other frameworks or applications. Perhaps we should call it `FRANKENPHP_DEBUG`?

### PR DESCRIPTION
**Pull request by chalasr**
Fixes #57

### CODE REVIEW

**Review by dunglas — APPROVED** [review]
LGTM! Could you open the same PR on Symfony Docker and API Platform, please?

**Comment by chalasr** [comment]
Are we sure we won't want to reuse this flag at some point for other purposes (non caddy related)? Otherwise `FRANKENPHP_DEBUG` might be more future proof. Just wondering 

>  Could you open the same PR on Symfony Docker and API Platform, please?

Sure!

**Comment by dunglas** [comment]
As this env var contains a string that will be injected in `Caddyfile`, I think it's good as-is.

**Comment by chalasr** [comment]
Alright then. Companion PRs: https://github.com/api-platform/api-platform/pull/2313, https://github.com/dunglas/symfony-docker/pull/31

**Review by maxhelias — APPROVED** [review]

**Comment by dunglas** [comment]
Thanks @chalasr!

**Pull request merged**
