### PR TITLE
ci: fix Docker Push

### PR DESCRIPTION
**Pull request by dunglas**
The build is currently failing: https://github.com/dunglas/frankenphp/actions/runs/3298679933/jobs/5441109651

### CODE REVIEW

**Comment by withinboredom** [comment]
You should just need to add a secret `REGISTRY_LOGIN_SERVER=docker.io`

**Comment by dunglas** [comment]
I've done it and it looks like it's not working.

**Comment by dunglas** [comment]
@withinboredom it looks like this fixed the build (probably just the image name). However, the "latest" tag is missing: https://hub.docker.com/repository/docker/dunglas/frankenphp/tags

**Comment by withinboredom** [comment]
IIRC, it only pushes [`latest` on tags](https://github.com/docker/metadata-action#latest-tag). So you'll have to create a new tag, or delete and recreate a tag on the updated main.

**Comment by withinboredom** [comment]
@dunglas, if only the secrets changed, simply rebuilding the tag will work.

**Comment by withinboredom** [comment]
Ah, it looks like you can add `type=raw,value=latest,enable={{is_default_branch}}` to the docker meta and it will "just work" on `main` branch pushes.

**Comment by dunglas** [comment]
I didn't change the token 😅

And PR welcome as usual :)

**Comment by withinboredom** [comment]
:joy: I just updated my fork, and builds are failing for me too. So two birds, one scone. :)

I'll get a PR together.

**Pull request merged**
